hl.on("hyprland.start", function()
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("clipse -listen")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaymc")
    hl.exec_cmd("hypridle")
end)
